version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:80" # cheeck 2
    networks:
      - bookstore-network
    image: "$env:DOCKER_USER/mernstack-frontend:latest" # Add this line for tagging

  backend:
    build:
      context: ./backend
    ports:
      - "5001:5000" # check
    networks:
      - bookstore-network
    environment:
      - NODE_ENV=production
    image: "$env:DOCKER_USER/mernstack-backend:latest" # Add this line for tagging

networks:
  bookstore-network:
    driver: bridge
